### PR TITLE
Bump reqwest to 0.8 and adjust code

### PR DESCRIPTION
**Pull request by twistedfall**

### CODE REVIEW

**Review by pfernie — CHANGES_REQUESTED** [review]
Looks like this needs some additional changes in reqwest_session.rs for the newer version of reqwest. `reqwest::Client::new()` no longer returns a `Result`, as can be seen in the CI failure.

**Comment by twistedfall** [comment]
True that, fixed

**Comment by twistedfall** [comment]
Will you please merge this PR? I've updated tests. The current failures have no relation to the changes in PR, they were failing before too.

**Review by pfernie — APPROVED** [review]

**Comment by pfernie** [comment]
Apologies for the very delayed response, missed the github notify on this. Merged; as you say, CI failures are unrelated, I will need to address, thx.

**Pull request merged**
